version: '3.5'
services:
  postgres:
    image: 'postgres:11'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  web:
    build: .
    environment:
      DBHOST: db
    ports:
      - "8080:8000"
    links:
      - "postgres:db"
volumes:
  postgres: