ansible_connection: local

vpc_name: bju-vpc
vpn_name: bju-vpn
vpc_key: bju-vpc
vpc_dns_zone: bju-vpc

aws_region: us-east-1 
aws_access_key: AKIAS4WH7EEOMRN5VZ5Y
aws_secret_key: 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

vpc_cidr_block: 10.0.0.0/16
vpc_asn: 64512
vpc_private_subnet:
  cidr: 10.0.2.0/24
  az: "{{ aws_region }}a"
vpc_public_subnet:
  cidr: 10.0.1.0/24
  az: "{{ aws_region }}a"
vpc_private_subnet_2:
  cidr: 10.0.3.0/24
  az: "{{ aws_region }}b"
vpc_public_subnet_2:
  cidr: 10.0.4.0/24
  az: "{{ aws_region }}b"

vpc_security_groups:
  - name: vpc
    description: "Allow internal traffic in the VPC"
    rules:
      - proto: all
        group_name: vpc
        ports: all
  - name: allow-public-ssh
    description: "Allow public SSH"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
  - name: allow-public-http
    description: "Allow public web traffic"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 80
          - 8080
          - 443