apiVersion: v1
kind: Service
metadata:
  name: "atc-test-service"
  namespace: "atc-project-test"
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app: "atc"