apiVersion: v1
kind: Service
metadata:
  name: "service-atc"
  namespace: "atc-project"
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app: "atc"